name: seoulful-client

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Generate Environment Variables File for Production
        run: |
          echo "NAVER_MAP_CLIENT_ID=${{ secrets.NAVER_MAP_CLIENT_ID }}" >> .env.production
          echo "NAVER_MAP_CLIENT_SECRET=${{ secrets.NAVER_MAP_CLIENT_SECRET }}" >> .env.production
          echo "KAKAO_REST_API=${{ secrets.KAKAO_REST_API }}" >> .env.production
          echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env.production

      - name: Docker 빌드 설정
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build & Push
        run: |
          docker build -t ${{ secrets.DOCKERHUB_REPO }}/seoulful-client:latest .
          docker push ${{ secrets.DOCKERHUB_REPO }}/seoulful-client:latest
